### PR TITLE
Interrupts

### PR DESCRIPTION
**Pull request by losipiuk**

### CODE REVIEW

**Comment by sopel39** [comment]
lgtm

**Comment by arhimondr** [comment]
lgtm

**Comment by kokosing** [comment]
Does presto jdbc have the same problem? If so create a pull request for presto as well.

**Comment by arhimondr** [comment]
@kokosing  Actually those changes are already in the mainstream presto JDBC. @losipiuk just moved them here.

**Comment by arhimondr** [comment]
Replaced with #13

**Pull request closed without merging**
